trigger:
- master
- feat/*
- feature/*

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Starting build.
  displayName: 'Run a one-line script'
- task: CmdLine@2
  inputs:
    script: |
      dir
- task: CmdLine@2
  inputs:
    script: call BuildCake.cmd
