trigger:
- master
- feat/*
- feature/*

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.201
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: PowerShell@2
  displayName: Build App
  inputs:
    filePath: 'build.ps1'      
