version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: 
      name: win/vs2019
      shell: cmd.exe
    steps:
      - checkout
      - run:
        command: buildcake.cmd
        shell: cmd.exe
