using System;
using System.Collections.Generic;
using System.Diagnostics;
using cdeLib.Infrastructure;
using FlatSharp.Attributes;
using MessagePack;
using ProtoBuf;

namespace cdeLib.Entities;

/// <summary>
/// Represents a 16-byte hash value as two 64-bit unsigned integers.
/// Uses readonly record struct for immutability, value semantics, and zero defensive copies.
/// </summary>
[DebuggerDisplay("HashA = {HashA}, HashB = {HashB}")]
[ProtoContract]
[FlatBufferStruct]
[MessagePackObject]
public readonly record struct Hash16
{
    [ProtoMember(1, IsRequired = true)]
    [FlatBufferItem(0)]
    [Key(0)]
    public ulong HashA { get; init; } // first 8 bytes

    [ProtoMember(2, IsRequired = true)]
    [FlatBufferItem(1)]
    [Key(1)]
    public ulong HashB { get; init; } // last 8 bytes

    /// <summary>
    /// Returns true if this hash has been set (non-zero value).
    /// Zero hash (both HashA and HashB are 0) is used as sentinel for "not set".
    /// </summary>
    [IgnoreMember]
    public bool IsSet => HashA != 0 || HashB != 0;

    /// <summary>
    /// Returns an empty/unset hash (all zeros).
    /// </summary>
    public static Hash16 Empty => default;

    /// <summary>
    /// Creates a Hash16 from a byte array (typically 16 bytes from MD5).
    /// </summary>
    public Hash16(byte[] hash) : this(
        BitConverter.ToUInt64(hash, 0),
        hash.Length > 8 ? BitConverter.ToUInt64(hash, 8) : 0)
    {
    }

    /// <summary>
    /// Creates a Hash16 from an integer (for testing).
    /// </summary>
    public Hash16(int hash) : this(0, (ulong)hash)
    {
    }

    /// <summary>
    /// Primary constructor for creating Hash16 from two ulongs.
    /// </summary>
    public Hash16(ulong hashA, ulong hashB)
    {
        HashA = hashA;
        HashB = hashB;
    }

    [IgnoreMember]
    public string HashAsString => ByteArrayHelper.Hash16ToHexString(HashA, HashB);

    public override string ToString() => $"A:[{HashA}] B:[{HashB}]";

    // Note: Equals and GetHashCode are automatically generated by record struct
    // with structural equality semantics (compares HashA and HashB values)

    /// <summary>
    /// Custom equality comparer for Hash16.
    /// Note: record struct provides structural equality, but this is kept for compatibility
    /// with existing code that may use it explicitly.
    /// </summary>
    public class EqualityComparer : IEqualityComparer<Hash16>
    {
        public bool Equals(Hash16 x, Hash16 y) => StaticEquals(x, y);

        public int GetHashCode(Hash16 obj) => StaticGetHashCode(obj);

        public static bool StaticEquals(Hash16 x, Hash16 y) =>
            x.HashA == y.HashA && x.HashB == y.HashB;

        public static int StaticGetHashCode(Hash16 obj) =>
            HashCode.Combine(obj.HashA, obj.HashB);
    }
}