name: .NET

on:
  push:
#    branches: [ "main","" ]
  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
            #fetch depth 0 or gitversion breaks since it can't obtain the required tags etc. 
            fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Build
        run: |
          ./build.ps1 publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: app
          path: artifacts/
